version: '3'
services:
  app:
    container_name: bff-web
    build: .
    volumes:
      - .:/go/src/app
    tty:
      true
    ports:
      - 7080:3000
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: redis:4.0.9
    volumes:
      - storage:/var/lib/redis
    ports:
      - "3379:6379"

volumes:
    storage:
